# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: install dependency
      run: npm install
    - name: install react-native
      run: npm install -g react-native-cli
    - name: linking file
      run: react-native link
    - name: Build with Gradle
      run: |
        cd ./android/
        echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
        gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch release.keystore.asc > app/homeplace.keystore
        ./gradlew assembleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v1
      with:
        # Artifact name
        name: app-release.apk
        # Destination path
        path: android/app/build/outputs/apk/release/
